export default {
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  LOAD_AUTHORS: "LOAD_AUTHORS",
  CREATE_AUTHOR: "CREATE_AUTHOR",
  UPDATE_AUTHOR: "UPDATE_AUTHOR",
  DELETE_AUTHOR: "DELETE_AUTHOR",
};
